version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: daily_blog_db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./daily_blog_dump.sql:/docker-entrypoint-initdb.d/daily_blog_dump.sql
      - ./wait-for-it.sh:/wait-for-it.sh

  backend:
    build: .
    container_name: daily_blog_backend
    ports:
      - "8000:8000"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_HOST: db
      DB_PORT: 3306
    depends_on:
      - db

volumes:
  mysql_data: